// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_activity from "./routes/api/activity.tsx";
import * as $books_id_ from "./routes/books/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $shelves from "./routes/shelves.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/api/activity.tsx": $api_activity,
    "./routes/books/[id].tsx": $books_id_,
    "./routes/index.tsx": $index,
    "./routes/shelves.tsx": $shelves,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
